services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      POSTGRES_DB: financeiro
      POSTGRES_USER: financeiro
      POSTGRES_PASSWORD: financeiro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: dev-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana
    container_name: dev-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
volumes:
  postgres_data: