services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      POSTGRES_DB: financeiro
      POSTGRES_USER: financeiro
      POSTGRES_PASSWORD: financeiro
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: financeiro-app
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/financeiro
      DB_USER: financeiro
      DB_PASSWORD: financeiro
    ports:
      - "8080:8080"