spring.application.name=financeiro


spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:financeiro}?user=${POSTGRES_USER:financeiro}&password=${POSTGRES_PASSWORD:financeiro}&sslmode=${POSTGRES_SSL:disable}
