spring.application.name=financeiro



management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

jwt.secret: "xpNaB2cZieWnQNesLVH1Vi6HzCqL+p7lSdJmiEq+9qk="
jwt.ttl-seconds: 3600

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financeiro}
spring.datasource.username=${DB_USER:financeiro}
spring.datasource.password=${DB_PASSWORD:financeiro}
spring.datasource.driver-class-name=org.postgresql.Driver